#!/usr/bin/env python3
"""Create a shareable static HTML page under pages/<slug>/index.html.

Typical use:
  python3 scripts/share_html.py --title "Demo" --file /tmp/demo.html --deploy

The deployed URL is printed at the end.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Iterable

REPO_URL = "https://fletcherd3.github.io/html-share"
ROOT = Path(__file__).resolve().parents[1]
PAGES = ROOT / "pages"
INDEX = PAGES / "index.html"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "page"


def unique_slug(base: str) -> str:
    slug = slugify(base)
    if not (PAGES / slug).exists():
        return slug
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"{slug}-{stamp}"


def read_input(args: argparse.Namespace) -> str:
    if args.file:
        return Path(args.file).read_text(encoding="utf-8")
    if not sys.stdin.isatty():
        return sys.stdin.read()
    raise SystemExit("provide --file PATH or pipe HTML on stdin")


def ensure_document(content: str, title: str) -> str:
    if re.search(r"<html[\s>]", content, flags=re.I):
        return content
    safe_title = html.escape(title)
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>{safe_title}</title>
  <style>
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.5; }}
  </style>
</head>
<body>
{content}
</body>
</html>
"""


def page_title(page_dir: Path) -> str:
    doc = (page_dir / "index.html").read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"<title>(.*?)</title>", doc, flags=re.I | re.S)
    if m:
        return re.sub(r"\s+", " ", html.unescape(m.group(1))).strip()
    return page_dir.name


def iter_pages() -> Iterable[Path]:
    if not PAGES.exists():
        return []
    return sorted(
        (p for p in PAGES.iterdir() if p.is_dir() and (p / "index.html").exists()),
        key=lambda p: (p / "index.html").stat().st_mtime,
        reverse=True,
    )


def rebuild_listing() -> None:
    PAGES.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    rows = []
    for p in iter_pages():
        title = html.escape(page_title(p))
        slug = html.escape(p.name)
        mtime = dt.datetime.fromtimestamp((p / "index.html").stat().st_mtime, dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        rows.append(f"<li><a href=\"./{slug}/\">{title}</a><small>{mtime}</small></li>")
    list_html = "\n".join(rows) or "<li><em>no pages yet</em></li>"
    INDEX.write_text(f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>html-share</title>
  <style>
    :root {{ color-scheme: light dark; }}
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; max-width: 880px; margin: 40px auto; padding: 0 20px; line-height: 1.5; }}
    h1 {{ letter-spacing: -0.03em; }}
    ul {{ list-style: none; padding: 0; }}
    li {{ display: flex; justify-content: space-between; gap: 16px; padding: 12px 0; border-bottom: 1px solid color-mix(in srgb, CanvasText 15%, transparent); }}
    a {{ font-weight: 650; }}
    small {{ opacity: .7; white-space: nowrap; }}
  </style>
</head>
<body>
  <h1>html-share</h1>
  <p>quick public html pages generated by oli.</p>
  <ul>
{list_html}
  </ul>
  <p><small>updated {now}</small></p>
</body>
</html>
""", encoding="utf-8")


def run(cmd: list[str]) -> None:
    subprocess.run(cmd, cwd=ROOT, check=True)


def maybe_deploy(message: str) -> None:
    run(["git", "add", "pages"])
    diff = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=ROOT)
    if diff.returncode == 0:
        return
    run(["git", "commit", "-m", message])
    run(["git", "push", "origin", "main"])


def main() -> None:
    parser = argparse.ArgumentParser(description="Create and optionally deploy a public HTML page.")
    parser.add_argument("--title", required=True, help="Page title, also used for slug when --slug is omitted")
    parser.add_argument("--slug", help="URL slug. defaults to a slugified title; made unique unless --replace")
    parser.add_argument("--file", help="HTML file to publish. If omitted, stdin is used")
    parser.add_argument("--replace", action="store_true", help="Overwrite pages/<slug>/index.html if it exists")
    parser.add_argument("--deploy", action="store_true", help="Commit and push after writing")
    args = parser.parse_args()

    slug = slugify(args.slug or args.title) if args.replace else unique_slug(args.slug or args.title)
    page_dir = PAGES / slug
    page_dir.mkdir(parents=True, exist_ok=True)

    content = ensure_document(read_input(args), args.title)
    (page_dir / "index.html").write_text(content, encoding="utf-8")
    rebuild_listing()

    url = f"{REPO_URL}/{slug}/"
    if args.deploy:
        maybe_deploy(f"add shared html page: {slug}")
    print(url)


if __name__ == "__main__":
    main()
